### ISSUE TITLE
For your consideration

### ISSUE THREAD

**Issue by jtsternberg** [tnorthcutt/wpawesome#3]
I'll let you decide if these are worth being decided.
https://github.com/jtsternberg/Shortcode_Button
https://github.com/jtsternberg/TwitterWP

**Comment by tnorthcutt** [comment]
Abso-freaking-lutely. Send a PR!

![daft-punk-thumbs-up-ok](https://cloud.githubusercontent.com/assets/796639/10892526/8aee14fa-8169-11e5-8e85-780816fda702.gif)
